#pragma once


#define IOCTL_PROCENUM_GET_PROCESS_LIST CTL_CODE( \
	FILE_DEVICE_UNKNOWN, 0X01, METHOD_BUFFERED, FILE_ANY_ACCESS )


typedef struct _PROCESS_DESC {
	HANDLE ProcessId;
	WCHAR ImageFileName[256 + 1];
} PROCESS_DESC, *PPROCESS_DESC;

typedef struct _PROCESS_DESC_LIST {
	ULONG procDescCount;
	PROCESS_DESC ProcessDesc[1];
} PROCESS_DESC_LIST, *PPROCESS_DESC_LIST;

